Repository Dhnillhaq/Project-Sistem-Peminjaman, pull requests merged in 2023-12, with the labels that each got.

#54 feat: change Flowchart
  project-team-flowchart.md
Labels: documentation, request to review

#55 feat: Integer input case, peminjaman, pengembalian and more
  Main.class
  Main.java
  project-team-flowchart.md
Labels: bug fix, documentation, chore, feature enhancement, request to review

#57 fix bug in digital book function
  Main.java
Labels: bug fix, chore

#58 chore: (management book)fix all bug scanner
  Main.class
  Main.java
Labels: bug fix, chore
