Repository Dhnillhaq/Project-Sistem-Peminjaman, pull requests merged in 2023-11, with the labels that each got.

#43 Feat: fix back to repo link
  project-team-flowchart.md
Labels: bug, documentation, invalid

#45 feat: add book stock
  Main.class
  Main.java
Labels: chore, feature enhancement, refactor, request to review

#46 Dhnillhaq
  Main.class
  Main.java
Labels: chore

#47 feat: Add Book Stock, fix validation, fix lending and return book
  Main.class
  Main.java
Labels: bug fix, chore, feature enhancement, request to review
